const bids = [
  {
    title: "Bid For AutoBid",
    content: [
      "❤️Hello❤️",
      "I have already done the same work that you want many times.",
      "As a professional Software Engineer, I have rich experience and depth knowledge of this field.",
      "While reading job description, I'm very exciting that this job seems to be posted for me.",
      "All required skills mentioned on job description are my strongest ones as well as I am very confident with them",
      "I could start to work immediately depending on your requirements.",
      "Looking forward to work on this project.",
    ],
  },
  {
    title: "Blockchain Bid",
    content: [
      "I am a senior blockchain developer with extensive experience in developing and deploying various types of blockchain applications such as SaaS apps, trading platforms, and NFT marketplaces on AWS, Azure, and Bluemix.",
      "I have completed numerous projects as a senior blockchain developer, some of which include:",
      "https://1inch.io/",
      "https://portion.io/",
      "https://app.camelot.exchange/",
      "In particular, I possess rich experience in building MEV bots that extract maximal value from transactions by scanning the mempool for specific transactions based on gas price, order routing, and other market conditions that could affect transaction costs.",
      "Once identified, the bot executes profitable trades by submitting its own transaction and reaping arbitrage opportunities.",
      "My skillset includes Solidity smart contract development with ERC-20, ERC-721, and ERC-1155, DApp, and API development with Javascript and Python (using web3.js and 0x.js), DAO creation, NFT project management with Solana and Rust, APTOS network with Move language, building trading bots, and web fullstack development with NodeJS, ReactJS, VueJS, and MongoDB.",
      "I am ready to commence work immediately, pending your specific requirements.",
      "I also have strong experience in building blockchain applications to track by connecting to the Hyperledger blockchain.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid For Front End",
    content: [
      "Hello",
      "I hope this message finds you well. I wanted to introduce myself as a frontend developer with prior experience working for various specialized and tailored web project.",
      "Over the years, I have successfully completed numerous frontend projects with utmost precision",
      "You can visit my Github page at : https://github.com/D0723",

      "https://minardilaw.com/",
      "https://www.massimpressions.com/",
      "https://www.russellbrand.com/",
      "https://www.moffett.com/",
      "https://expertpt.co.uk/",
      "https://nygaragedoorsrepair.com/",
      "As a professional web developer, I possess extensive knowledge and proficiency in React, Vue, Angular, as well as design tools such as Figma, XD, and PSD. With a deep understanding of these technologies, I am fully prepared to begin working on your project immediately, tailored to your specific requirements.",
      "I am ready to commence work immediately, pending your specific requirements.",
      "In all my endeavors, I prioritize quality over quantity and strive to establish long-term relationships with clients. Constructive criticism is highly appreciated, as it allows me to constantly improve and deliver exceptional outcomes.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid For Figma to HTML",
    content: [
      "❤️Hello❤️",
      "As a professional web developer, I have rich experience and depth knowledge of React, Vue Angular with Figma, XD, PSD",
      "I could start to work immediately depending on your requirements. And I'll provide a full-responsive Website on all devices (Desktops, Laptops, Tablets, Mobiles)",
      "I believe in quality over quantity, and I respect all reviews and criticisms about my work and I spend the most effort on providing the best result.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid For Laravel",
    content: [
      "❤️Hello❤️",
      "As a professional web developer, I have rich experience and in-depth knowledge of Laravel. You can check my past Laravel works: ",
      "I have completed numerous projects as a senior Laravel developer, some of which include:",
      "https://minardilaw.com/",
      "https://www.massimpressions.com/",
      "https://www.russellbrand.com/",
      "https://www.moffett.com/",
      "https://expertpt.co.uk/",
      "https://nygaragedoorsrepair.com/",
      "I am ready to commence work immediately, pending your specific requirements.",
      "In all my endeavors, I prioritize quality over quantity and strive to establish long-term relationships with clients. Constructive criticism is highly appreciated, as it allows me to constantly improve and deliver exceptional outcomes.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid for WordPress",
    content: [
      "❤️Greeting❤️",
      "I have the exact match with the skills you are looking for a current project.",
      "I have completed 100+ projects.... without letting down a single Client......",
      "As Many Clients are still in touch based on my Working strategies and their satisfaction on their all previous Projects.",

      "Kindly have a look at some of my previous work samples:",
      "https://whalies.club",
      "https://riotflavours.com/",
      "https://atctower.com/",
      "https://stanbranding.com/",
      "https://startempirewire.com",
      "https://seattleshoulderdoc.com",

      
      "I am ready to commence work immediately, pending your specific requirements.",
      "In all my endeavors, I prioritize quality over quantity and strive to establish long-term relationships with clients. Constructive criticism is highly appreciated, as it allows me to constantly improve and deliver exceptional outcomes.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid For Full Stack Developer",
    content: [
      "❤️Hello❤️",
      "I can surely help you develop a fully functional website as per your requirement with 100% job satisfaction. ",
      "I am a ⚡creative freelancer⚡ and Since 2012, I am managing Software Development tasks successfully. and I have more than 👍10 years of Full stack experience and development for different companies in  👍Europe.  As a highly skilled Full-Stack Web developer with 6+ years of working experience. ",

      "⭐ Web ⭐",
      "✔️ Frontend : AngularJS, ReactJS, VueJS, Gatsby, Typescript",
      "✔️ Backend : PHP/Laravel-CodeIgnitor-YII2, Python/Django, Node.js/Express, Ruby/Ruby on Rails, C#/ASP.NET, GraphQL",
      "✔️ Database : MySQL, NoSQL Couch & MongoDB, SQLite, PostgreSQL",
      "✔️ Some more",
      "★ C/C++, C#, Java, Python, R, Go, Rust, Ruby, Dart",
      "★ Software Architecture, Algorithm, Web Scraping",
      "★ PSD to HTML, AJAX, Javascript, Responsive Design",
      "★ PHP, HTML, jQuery, Bootstrap, SCSS, CSS and Less",

      "Kindly have a look at some of my previous work samples:",
      "https://whalies.club",
      "https://riotflavours.com/",
      "https://atctower.com/",
      "https://stanbranding.com/",
      "https://startempirewire.com",
      "https://seattleshoulderdoc.com",

      
      "I am ready to commence work immediately, pending your specific requirements.",
      "In all my endeavors, I prioritize quality over quantity and strive to establish long-term relationships with clients. Constructive criticism is highly appreciated, as it allows me to constantly improve and deliver exceptional outcomes.",
      "I am available to start your project immediately and would be happy to discuss further details via a quick call or chat at your convenience.",
      "Best regards",
    ],
  },
  {
    title: "Bid For Game Developer",
    content: [
      "❤️Hello❤️",
      "how's it going, I hope you are doing well and staying safe.",
      "I am Professional Game Developer.",
      "I have read your project description seriously.",
      "I really want to participate in this work, and if I do, I feel like I can achieve amazing results.",
      "With 8 years of Unity experience for global businesses, I offer the technical expertise you might be looking for.",
      "Known for creating robust, high-speed web and mobile Games, my game development work has helped grow revenues, accelerate customer acquisition, increase game traffic and deliver an industry-leading competitive advantage. I highly value quality over quantity and I put a big effort to create a truly qualified product.",
      "I love pixel-perfectness, responsiveness and enjoy writing tests.",
      "This had been an important factor that made my previous projects successful.",

      "Please review my resume, which provides details of these projects and examples of skills in:",
      "- Game development using Unity, C# Programming.",
      "- Unreal Engine, Blueprint",
      "- Translation of wireframes and rapid prototyping tools to accurate, working code",
      "- Server Backend Programming using PUN2",
      "- AR/VR game by Oculus Quest.",

      "If my skills and experience match your requirements, just click chat button to discuss your project details.",
      "I am willing to take a technical interview, technical test, or trial project, to verify myself.",
      "Best Regards.",
    ],
  },
];
